DiscardOriginAttestation-2021 {
    iso(1) member-body(2) us(840) rsadsi(113549) pkcs(1) pkcs9(9) smime(16) mod(0)
    666 }

DEFINITIONS EXPLICIT TAGS ::=
BEGIN

id-ct-DiscardOriginAttestation OBJECT IDENTIFIER ::= {
    iso(1) member-body(2) us(840) rsadsi(113549) pkcs(1) pkcs-9(9) id-smime(16) id-ct(1)
    666 }

id-ct-BgpCommunity OBJECT IDENTIFIER ::= {
    -- perhaps something else than a PEN
    iso(1) org(2) dod(6) internet(1) private(4) enterprise(1)
    jobsnijders(41948) bgp(179) attr(1) classic(8)
}

id-ct-BgpLargeCommunity OBJECT IDENTIFIER ::= {
    -- perhaps something else than a PEN
    iso(1) org(2) dod(6) internet(1) private(4) enterprise(1)
    jobsnijders(41948) bgp(179) attr(1) large(32)
}

DiscardOriginAttestation ::= SEQUENCE {
    version		[0] INTEGER DEFAULT 0,
    asID		SEQUENCE SIZE(1..MAX) OF ASID,
    ipAddrBlocks        IPListRange,
    communities		SEQUENCE SIZE(1..MAX) OF Community }

ASID ::= INTEGER

IPListRange ::= SEQUENCE (SIZE(1..MAX)) OF IPAddressFamily

IPAddressFamily ::= SEQUENCE {
    addressFamily        OCTET STRING (SIZE(2..3)),
    addressesOrRanges    SEQUENCE OF IPAddressOrRange,
    prefixLengthRange    PrefixLengthRange OPTIONAL } -- if omitted, assume hostroutes
PrefixLengthRange ::= SEQUENCE {
    minlength		 INTEGER,
    maxlength            INTEGER
}

IPAddressOrRange ::= CHOICE {
    addressPrefix        IPAddress,
    addressRange         IPAddressRange
}

IPAddressRange ::= SEQUENCE {
    min  IPAddress,
    max  IPAddress }

IPAddress ::= BIT STRING

Community ::= SEQUENCE {
    communityType	OBJECT IDENTIFIER, -- id-ct-BgpCommunity or id-ct-BgpLargeCommunity
    communityValue	OCTET STRING }

END
