[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm[toml]>=6.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
tag_regex = '^(?:[\w-]+-)?(?P<version>[vV]?\d+(?:\.\d+){1,2}[^\+]*)(?:\+.*)?$'
local_scheme = "no-local-version"
